global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using DatabaseAccess.Entiteti;
global using DatabaseAccess.DTOs;
global using NHibernate;
global using static DatabaseAccess.Extensions;
global using System.Diagnostics.CodeAnalysis;